### ISSUE TITLE
Idea: Exclude text in parentheses for category assignment

### ISSUE THREAD

**Issue by dasnessie** [tstehr/shoppinglist#100]
We recently talked about excluding text in parentheses for saving the items in the suggestion list. Here's a slightly less invasive idea based on that: If I have `apples` in my suggestion list as `fruit & veg`, and I add  `apples (small)` to the list, could it be assigned to `fruit & veg` by default? 

I would still like to be able to save `(P) pasta` and `(ETC) pasta (whole grain, organic market)` to my suggestion list as different items. In that case (assuming they are the only two items on my list), I'd expect any new item `pasta (foo)` to be assigned to the (P) category. I don't have an opinion yet on what should happen if there is only `(ETC) pasta (whole grain, buy at organic market)` on the list and I add `pasta`.

Thoughts?

**Comment by tstehr** [comment]
That sounds like a nice quality of life improvement, I'll look into implementing it.
