### ISSUE TITLE
Hint text misses newline

### ISSUE THREAD

**Issue by sonea-pm8** [tstehr/shoppinglist#12]
In Firefox on Android, the newlines in the hint text of the extended input field are not shown. Maybe bug in Firefox?

**Comment by sonea-pm8** [comment]
In chrome, the newlines are fine.

**Comment by tstehr** [comment]
Apparently Chrome is actually in the wrong here

> The placeholder attribute represents a short hint (a word or short phrase) intended to aid the user with data entry when the control has no value. A hint could be a sample value or a brief description of the expected format. **The attribute, if specified, must have a value that contains no U+000A LINE FEED (LF) or U+000D CARRIAGE RETURN (CR) characters.**

— https://www.w3.org/TR/2017/REC-html52-20171214/sec-forms.html#the-placeholder-attribute 

See also https://stackoverflow.com/a/7312658, will probably need fake placeholder behind the textarea.
