### ISSUE TITLE
escape to close modal dialogues

### ISSUE THREAD

**Issue by AberDerBart** [tstehr/shoppinglist#28]

**Comment by tstehr** [comment]
Implemented by 2a467d6eebcb2e9ebd8c81216b1b852ac6506ed8

**Comment by AberDerBart** [comment]
still doesn't work for me (firefox 60.0.2, Linux)

**Comment by tstehr** [comment]
Yeah, I forgot to relaunch the online instance. Please recheck and comment if it still doesn't work

**Comment by AberDerBart** [comment]
works like a charm, thank you!
