### ISSUE TITLE
In firefox mobile, the page is wider than the screen

### ISSUE THREAD

**Issue by dasnessie** [tstehr/shoppinglist#48]
In firefox mobile, the page is wider than the screen, with a weird empty space on the right.

![image](https://user-images.githubusercontent.com/43586524/60402273-a7d5a000-9b8d-11e9-85ec-116c6ab84605.png)

**Comment by tstehr** [comment]
Does this happen on all lists, or only on this specific one?

**Comment by dasnessie** [comment]
It happens on all lists to which I add "(F) 3 Glas getrocknete Tomaten in Öl", with a screen didagonal of 10,85 cm, 960×540 px. It's the history's fault - the history entry is too wide.

**Comment by tstehr** [comment]
Thanks for the detailed description, should be fixed now
