### ISSUE TITLE
Further improvement to "Add to home screen"

### ISSUE THREAD

**Issue by Invisible4ever** [tstehr/shoppinglist#71]
Option to create an app that is a single shopping list?

Currently whichever list is transformed to an app makes the app start in the root location instead of starting in the shopping list.

![photo_2020-10-18_12-19-47](https://user-images.githubusercontent.com/8517542/96364716-49468380-113c-11eb-98dd-80b44ffa160e.jpg)

**Comment by tstehr** [comment]
I've added an option to the home view that allows you to always open with the previously opened list:

![restoration](https://user-images.githubusercontent.com/1938293/96376831-7b2e0900-1181-11eb-8db3-ec146f83cb76.png)

**Comment by Invisible4ever** [comment]
My use case were two different lists, each of which I wanted as a home view. That is still not possible, but I approve; I have only a single list nowadays. :)
(Just now found the option :D)

**Comment by tstehr** [comment]
You could probably add the app to the Home Screen twice ;) On iOS at least each PWA instance has separate storage, and would thus remember it’s respective list.
